# -------------------------------------------------------------------------------------
# Author Configuration | 作者配置
# -------------------------------------------------------------------------------------

name = "haiyux"
email = "haiyux@foxmail.com"
link = "https://haiyux.cc"
avatar = "/avatar.png"
